---
all:
  children:
    application:
      hosts:
        debian-stretch:
  vars:
    ansible_become_method: su
    node_architecture: linux-x64
    private_network_interface: enp0s3
    public_network_interface: enp0s8
    running_locally: true
